"""
housing/apps.py

This file is auto-generated by 'python manage.py startapp housing'.
The class name (HousingConfig) and the 'name' field ('housing') must
match what's in INSTALLED_APPS in settings.py.

We registered it as 'housing' (the short form). Django finds this file
automatically and uses HousingConfig. Both forms work:
  - 'housing'                        ← short form (what we use)
  - 'housing.apps.HousingConfig'    ← explicit form (same result)
"""

from django.apps import AppConfig


class HousingConfig(AppConfig):
    default_auto_field = "django.db.models.BigAutoField"
    name = "housing"
