# Generated by Django 5.2.10 on 2026-02-04 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0003_alter_agent_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyimage',
            old_name='property',
            new_name='listing',
        ),
    ]
